trigger:
- main

pool:
  name: Default

variables:
  TF_VERSION: '1.6.6'

stages:

# ---------- STAGE 1: INIT ----------
- stage: Init
  jobs:
  - job: InitJob
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: AzureCLI@2
      displayName: Terraform Init
      inputs:
        azureSubscription: 'my-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init


# ---------- STAGE 2: PLAN ----------
- stage: Plan
  dependsOn: Init
  jobs:
  - job: PlanJob
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: AzureCLI@2
      displayName: Terraform Plan
      inputs:
        azureSubscription: 'my-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init
          terraform plan


# ---------- STAGE 3: APPLY ----------
- stage: Apply
  dependsOn: Plan
  jobs:
  - job: ApplyJob
    steps:

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: $(TF_VERSION)

    - task: AzureCLI@2
      displayName: Terraform Apply
      inputs:
        azureSubscription: 'my-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          terraform init
          terraform apply -auto-approve