trigger:
- main

pool:
  name: Default

variables:
  TF_VERSION: '1.6.6'

stages:

# ---------- STAGE 1: INIT ----------
- stage: Init
  jobs:
  - job: InitJob
    steps:

    - script: |
        echo "Installing Terraform..."
        wget https://releases.hashicorp.com/terraform/$(TF_VERSION)/terraform_$(TF_VERSION)_linux_amd64.zip
        unzip terraform_$(TF_VERSION)_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        terraform -version
      displayName: Install Terraform

    - script: terraform init
      displayName: Terraform Init

# ---------- STAGE 2: PLAN ----------
- stage: Plan
  dependsOn: Init
  jobs:
  - job: PlanJob
    steps:

    - script: terraform init
      displayName: Terraform Init

    - script: terraform plan
      displayName: Terraform Plan

# ---------- STAGE 3: APPLY ----------
- stage: Apply
  dependsOn: Plan
  jobs:
  - job: ApplyJob
    steps:

    - script: terraform init
      displayName: Terraform Init

    - script: terraform apply -auto-approve
      displayName: Terraform Apply